### PR TITLE
Fix some misc issues

### LINKED ISSUE #23: tnnt_globals.dark_rooms_lit won't tick if standing on a non-ROOM tile
Instead, it should probably check the roomno of the room you're standing in rather than the terrain type. Or possibly iterate over all squares being lit up and check *their* roomnos rather than where the player is standing, allowing for you to light two dark rooms at once with the right positioning and line of sight?

Extra credit: make lighting the Big Room count as lighting a room (but only once for the entire level).

### LINKED ISSUE #24: Nazgul killed counter (and possibly other kill counters) don't use the same data as the achievement
tnntstats uses `mvitals[PM_NAZGUL].died` to show "number of nazgul killed" but the actual achievement is based on `mvitals[PM_NAZGUL].ukilled`. Thus you can somehow get it saying 9/9 Nazgul killed but not get the achievement.

### LINKED ISSUE #25: Beast Master achievement triggers when you hatch an egg and it is tame
This isn't really what the achievement means by "not using food". Especially since the monster was food right up until it hatched.

### LINKED ISSUE #26: Swap chest objects don't retain their opoisoned value
Not much reason why they shouldn't; it would be nice to give someone a stack of poisoned +7 silver darts instead of just boring normal +7 silver darts.

opoisoned is an alias for otrapped, but most (all?) of the objects for which otrapped is relevant don't go into the swap chest anyway.

### PR DESCRIPTION
**Pull request by entrez**
Try to close some issues @copperwater opened

Fixes #23 
Fixes #24 
Fixes #25 
Fixes #26

### CODE REVIEW

File: src/music.c [hunk 1]
```diff
@@ -225,19 +225,26 @@ charm_monsters(distance)
...
+            was_tame = mtmp->mtame;
             mtmp2 = mtmp->nmon;
             if (DEADMONSTER(mtmp))
                 continue;
 
             if (distu(mtmp->mx, mtmp->my) <= distance) {
                 if (!resist(mtmp, TOOL_CLASS, 0, NOTELL))
                     (void) tamedog(mtmp, (struct obj *) 0);
+                if (!was_tame && mtmp->mtame)
+                    tnnt_achieve(A_TAMED_NOT_BY_FOOD);
```
Comment (copperwater) [inline src/music.c:247]: Problem with splitting it up into separate cases is that they might get missed. At least one I can think of: getting charismatic from a magic trap with adjacent monsters.
